name: Install dependencies

inputs:
  node-version: { required: true }
  couchdb-version: { required: false, default: '3.1' }

runs:
  using: composite
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
    - run: yarn install # --frozen-lockfile TODO get this option working
