name: CI

on: [push, pull_request]

permissions:
  contents: read

runs-on: ubuntu-latest

jobs:
  lint:
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: yarn install # --frozen-lockfile TODO get this option working
      - run: yarn lint
  test-js:
    timeout-minutes: 10
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node:
          # - '10' dropped support due to error postgres-array@3.0.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
          - '12'
          - '14'
          - '16'
          - '18'
          - '20'
    name: test js - node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install # --frozen-lockfile TODO get this option working
      - run: yarn test
  test-ts:
    timeout-minutes: 10
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node:
          # - '10' dropped support due to error postgres-array@3.0.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
          - '12'
          - '14'
          - '16'
          - '18'
          - '20'
    name: test ts - node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install # --frozen-lockfile TODO get this option working
      - run: yarn test-ts
